name: Nova Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - nova-test
concurrency:
  group: nova-ci-cluster
  cancel-in-progress: false
jobs:
  nova-test:
     runs-on: [ self-hosted ]
     steps:
       - name: Fetch
         uses: actions/checkout@v5
       - name: Build
         run: |
           time KBUILD_BUILD_TIMESTAMP='' make LLVM=1 CC="ccache clang" -j 32
           time make modules_install INSTALL_MOD_PATH=~/buildroot/modules/usr
           cd ~/buildroot && make
       - name: Provision
         run: |
           get_leases() {
             echo "Checking leases..."
             colossus bm lease list -j | jq -r '.[] | select(.entity_details.leaseJustification // "" | contains("Nova CI/CD")) | "\(.entity_details.id),\(.entity_details.status),\(.entity_details.ipAddress),\(.entity_details.leaseJustification)"' | tee leases.txt
           }
           get_leases
           grep -v -f <(cut -d, -f5 leases.txt) target-gpu-arch.txt | xargs -I{} colossus bm lease create -d 7d -agb main -agu https://gitlab-master.nvidia.com/epeer/nova-test.git -apb target.yml -lj "Nova CI/CD,{}" -o ubuntu-25.10-x86_64-standard-uefi -f "gpus.architecture={}" "cpus.sockets.arch=x86_64"
           while grep -v -f <(cut -d, -f5 leases.txt) target-gpu-arch.txt || grep -v RESERVED leases.txt >/dev/null; do
              sleep 30
              get_leases
           done
       - name: Deploy
         run: |
           SSH_OPTS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o ServerAliveInterval=2 -o ServerAliveCountMax=1"
           while IFS= read -r TARGET; do
             IP=`echo ${TARGET} | cut -d, -f3`
             scp ${SSH_OPTS} /nova/gpu-runner/_work/linux/linux/arch/x86_64/boot/bzImage root@${IP}:/
             scp ${SSH_OPTS} ~/buildroot/output/images/rootfs.cpio root@${IP}:/
             echo "Loading kexec kernel on ${IP}..."
             ssh -n ${SSH_OPTS} root@${IP} 'kexec -l /bzImage --initrd=/rootfs.cpio --append="ignore_loglevel console=ttyS1,115200n8"'
             echo "Booting kernel..."
             ssh -n ${SSH_OPTS} root@${IP} "kexec -e" || true 
           done < leases.txt
           echo "Waiting for boot to complete..."
           sleep 30
       - name: Test
         run: |
           while IFS= read -r TARGET; do
             IP=`echo ${TARGET} | cut -d, -f3`
             GPU_ARCH=`echo ${TARGET} | cut -d, -f5`
             ssh -n -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${IP} "journalctl && avocado run /root/driver-load-test.sh --tap -" | tee -a ${GPU_ARCH}.tap
           done < leases.txt
       - name: Summarize
         uses: pcolby/tap-summary@v1
       - name: Status
         run: |
           if cat *.tap | grep "^not ok"; then
             exit 1
           else
             echo All Tests PASSED!
           fi
       - name: Cleanup
         if: always()
         run: |
           while IFS= read -r TARGET; do
             ID=`echo ${TARGET} | cut -d, -f1`
             echo "Rebooting ${ID}..."
             colossus bm reboot --resource-id ${ID}
           done < leases.txt
           echo "Waiting..."
           sleep 180
